# To be placed in a downloads directory and renamed to "rulesXX.toml"
# where XX is a 2 digit zero padded number

mode = "Extensions"

Documents = [ ".pdf", ".doc", ".docx", ".html", ".epub", ".mobi", ".txt"]
Pictures = [ ".jpeg", ".jpg", ".png", ".bmp", ".gif", ".svg"]
Archives = [ ".zip", ".7zip", ".tar", ".bz", ".gz", ".xz", ".bz2"]
Videos = ['.webm', '.mpg', '.mp2', '.mpeg', '.mpe', '.mpv', '.ogg', '.mp4']
ProgramFiles = [".py", ".jar", ".crx", ".cpp", ".run", ".so", ".deb", ".java"]
DiskImages = [".iso", ".img"]
